version: '3.4'

services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: 1234
        ports:
            - 5432:5432

    migration:
        build:
            context: .
            dockerfile: migrationUtility.Dockerfile
        depends_on:
            - db
    
    app:
        build:
            context: .
            dockerfile: AnimeList/Dockerfile
        depends_on:
            - db
            - migration
        ports:
            - "80:8080"
            - "443:443"