version: '3.4'

services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: ANIME_LIBRARY
        ports:
            - 5432:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

    
    app:
        build:
            context: .
            dockerfile: animeList.Dockerfile
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8081:80"
            - "8082:443"